skip_branch_with_pr: true

environment:
  GO_VERSION: 1.16.3
  GO_TAGS: --tags release
  GITHUB_TOKEN:
    secure: YaLowdy+gBGyQ/DIQZbWJHpfCXVULmnDhdskAocjptsisGreS5G7EdcxYbD3Y0zP
  DOCKER_REGISTRY_USER:
    secure: FVuOZCmVWVrpfypCJ+Ngq8AffZnbTMM347aCPgyvo3I=
  DOCKER_REGISTRY_PASS:
    secure: 0GTn/dGoUn/PwyV6xrfvNKAenG/r0ZErtclQN3Gr6bQ=
  GCR_SA_JSON:
    secure: DrdW/oHH1ojGVsZLCSojYfdQqiHWHs6J6Tyy8uxovFTqg7f1s7hoZRLFYH5QM9KhtdTIXqOtpeLKS9pRhudUyI7fJfv4IyXVUhb7XQVqyBlrzHx3yitO8K5UW1a3t07xnBTSdPfv16kqi8bip1Mx0eja2cyHSTDE7HjfPeV0wAyeUyroelnInSgRg+iY+BXyOi+nc3ibeYp5VA1stEDTficqPIJIe7CX9XjZsM1DJIzYRmwGJgXK/4DG0NU7g15BEewh+OOAw4AlaYPBLJsbbt+L+dEJRZZ0w1SGTvhHG0w/m8RMdjYaMo2SigLAfIlJkZ/qMz9p9IU5XHmRW8NZHn91Q9feIazr8P58xkrW4q0GqJ3ER7S0EN646Hm4L+ao3ZCM/ZsjAYtfBXExTjjEXneNIRXDuO1MJ4LyAC9HnHe/kx7/+c87X43rsWMnkajgPsxiC5Jmrmz1ZPPrd7TB0FdS77tndFYpICF4IKrPSmQvAPGxp848ZK2uCrChQ0xNlupL11jvdJoGeCmldFQ2RW1lW4RgzleqGs6tJKi7oUlpfiSvkZUswgQeh1eL7d/Pqul0sATCPIgWofohqHZz817b9AtMgaQQUQpspSJmfj20doFOG6l16WLnaxJowqSdeh+g8R40Rwgm678o0XYSUBFraiQfoCJyPRbemEnmi1SeBDLJ8IzHkmTyibfqf3t1ccsVqueB+Km8Jr6CsmDUlPNYJi2oQqpZ3mxD7jnC3UCv5gIiYhcgSfyv/VtCimh60jnDSXqkyEu195OAv64NX+cL5o56Xq0uFFfoeWdVj28nDn5+a02kAWYr5rcDoXZNXV8CrAtQedxGYlbqVTnTNj0d66pQvzNWrRYP9VI1mwes3pdT3ih3wuwBamXfd3mfrynO6h+pxwHIU8xZ0D5Rkfj5QzcdLrfPJwAgDRHyRvT/YVwluk+mY2haMGog0qz2GAjbFBOGpxTi6it8zu/U5VCNi56UZg+KwGoRDgd3hOMbF/o4qJ0CVrLKNpot48BgKZjEOLvrkhHcRR6nYkdEtoEZkVT7YOKBfaQaddQ/ozs3MsVp5XJRE21zV6XLgbLf+70KtnVjicn+Q0wRWlAat15zPVyb9BosEcsho59ZzXv6f3kRFGMVGtwF3GjoZZ8aPDOF/99KI/Vx8cw3VtSqu1ekDxiQ2ozebrXiLiLdA6Nyv4kvSwjqeaUKpgTtTOCXC+XmxU+6U1Kix93L82jg+2KRUReQkuBro3pIQ4V1v4Kq8wsDIiOaf7aHNh1yvAbZI+dsFfpyc+eUgZfQINMP5lAkBJ8Ey5SSeEdLJQhBfOymadrHFCUWE8rte1jggBnEyu2p/eXJDXGbpPY93lqXtbgCSx0eXtqH+MQbIPycEcsR4Pqkste6DvMyoA/mXJqSdHtPsEHx/wOwCTNl4y5TyhyJAWiIAJjH1sJUU9rfVYxMX7pLsvmTAjTRmk6WXrUnzagQESeLzC2HWyNrWWvkLblYoLO4RRNVTEdb0nBDVVWEK85tFbGfO/Dkq5cj/y5gDrx05jqLHgwcMY+lQb8qm9iJuORygsn5LYH9pKiw/MV5Ib7TVmiNMvkmN61F3b/EBYxZ+sTRXgUhyhil3R2eMete5e8+hLByaK6qYxfklsZdF7NN2LbLS0o1+6CHZf1TiZK01E/EEBTRh47PumPq56Lf2ntMFlmEZkWwoImoaH8rYdT/cbC2FQuwn/AW1qHiLiwp5wOUcUggYiPHkT77AdEBNIKK6sklJ4/tF9qIkCRfot+0J0um29vgt1C6grMIbPymY+xl1HNFWJO5v3j+2hl2xDZNS0ZBGzMWwZ9rZIAzmb/pGeX0pWXbbZ8N0LvDIpQNeGD7hPr4ANBbyuaqfsoGtJYWNZPJLoO8/2SSN3+uVlGe2sOwzixIoIhvzUjKSNS8WbjfBh9I+2GF7TK+C7++Cy99v8L1GsjswrBAS5z0TZrgp4EGv5tAOIiB6aY6V2FLk/yTO5RVk9fJ6mdxYvtV1+6GzaD9oksvzmGk/47luH75eZboskL3B0vx+kP4fLINXMuBBceVxpHBa398FGXCzsv2Iq0fQqCd7avW5Dv6XtQxa764H7HW2ZfZpEmyqph/HU0whR6a9hzSxQR9J3FFoVUvXU1pZ0y4MavssKoRdu1+Z6QI3wm8US4S4eBgU3SPMgwEWDE2nu2DaDCNgP1wwSGI0UVlydOY3Ntlu8v8zThSwIQGAeTe1MZtBnnZVIpIVFfNeTy7YG1b+qrqpvRCvD9d9+Hc3mMS8S/z/cJHe5R6ZwCqBLqGdX+YfJXzaRYcTeozNybmswMXjylzonPb90oJqeYpuIN7MzUYhPoz3Hem7a/MKhFQeJcC5+1A58wtZVdlAKJs5YvN805tjckmwWTy1ULlhQwToZsJBzy4otOV7Ae+Of+B+jA9UW4yJZCnpihq509KpW2pV9Ea34WjrrtP6jEyAvrJ0w/s1yWUyLb/4IwsYOXlVr4ugRLXhb23S2zBEYlt6I2PGFGowvKZF6hAprowaXoqoG17pMJ27Wp4t5OrxG3t2mgL1uad2BXUGQwrA+DESARnfug9LgEE/sCxFWv4cjumTaUWXP8L+9W5Lrq4Mj5Dh7+HEH+5Zk1h6zgE5/n4Qmo/fWUbH3zlpXFYQM2EVtngEo8Xc5IMVBD/hcEH1dwziBI0cprom3+aowcmKd2HFl0DR4V9FHrQ8QOZ8aJmocfarTaKW8wDpcDby2pwt7uhmc1oeRFmMK+X/7RaTl2q6grTCigi1ZwCc7DlZW2l6LELYykZrQ56VvJj+DfqiQdXVrNsilUijZZphMdUj8cEpe36lQFnbzvt1N26A5cozm1zQcaHCz04zGZfyko2/aqEE5qgXjFL/9AFmmQ9iTMkURfAIUTjU3JjRH+jD0pNqUCoJfpMR+j4+ZBhukhyYGzZGwHgtbTYGpJrrxAjatJJN1oqLgyKR+y0RsnFHRfG45sn/VnfYl0=

  matrix:
    # - job_name: Windows
    #   job_group: tests
    #   APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

    # - job_name: Linux
    #   job_group: tests
    #   APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu

    # - job_name: macOS
    #   job_group: tests
    #   APPVEYOR_BUILD_WORKER_IMAGE: macOS

    - job_name: Release
      job_depends_on: tests
      APPVEYOR_BUILD_WORKER_IMAGE: ubuntu1804-master-gce-us-central1

matrix:
  fast_finish: true
  
for:
  
# ======================================
#      Release
# ======================================

-
  matrix:
    only:
    - job_name: Release
  
  init:
  - appveyor version

  install:
  - gvm install go${GO_VERSION} -B
  - gvm use go${GO_VERSION}
  - go version
  - bash ./install_goreleaser.sh
  - goreleaser --version
  # - sh: |
  #    sudo snap install --classic goreleaser
  #    goreleaser --version

  build_script:
  - nvm use 12
  - cd client
  - yarn
  - GENERATE_SOURCEMAP=false yarn build
  - ls -alR build
  - cd ..
  - mkdir internal/server/content
  - cp -r client/build/* internal/server/content
  - sh: |
      if [[ "$APPVEYOR_REPO_TAG" == "true" ]]; then
        goreleaser
      else
        goreleaser --snapshot --skip-publish
      fi

  test: off